export const ROUTES = {
  HOME: '/',
  INICIO: '/inicio',
  EXPLORAR: '/explorar',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  AUTH_CALLBACK: '/auth/callback',
  FAVORITES: '/favoritos',
  MY_PUBLICATIONS: '/mis-publicaciones',
  MESSAGES: '/mensajes',
  NOTIFICATIONS: '/notificaciones',
  SETTINGS: '/configuracion',
  PROFILE: '/perfil',
} as const
