export const PROPERTY_DETAIL_LABELS = {
  notFound: 'Propiedad no encontrada',
    noImages: 'Sin imágenes',
    bedroom: 'hab',
    bathroom: 'baños',
    squareMeter: 'm²',
    paymentDay: 'Fecha pago: día 1',
    details: 'Detalles',
    price: 'Precio',
    contact: 'Contactar',
    host: 'Anfitrión',
    memberSince: 'Miembro desde',
    seeHostProfile: 'Ver perfil del anfitrión',
    location: 'Ubicación',
    amenities: 'Amenidades',
    houseRules: 'Reglas del lugar',
    petAllowed: 'Mascotas permitidas',
    noPets: 'No mascotas',
    noSmokers: 'No fumadores',
} as const;