export const PROFILE_FORM = {
  AGE: {
    MIN: 18,
    MAX: 99,
  },
  BUDGET: {
    MIN: 0,
  },
  BIO: {
    MAX_LENGTH: 280,
    TEXTAREA_ROWS: 4,
  },
  AVATAR: {
    MAX_SIZE_BYTES: 3 * 1024 * 1024,
    ACCEPTED_TYPES: ['image/jpeg', 'image/png', 'image/webp'] as const,
  },
  ID_DOCUMENT: {
    MAX_SIZE_BYTES: 5 * 1024 * 1024,
    ACCEPTED_TYPES: ['image/jpeg', 'image/jpg', 'application/pdf'] as const,
    VALIDATION: {
      FILE_TYPE: 'Formato no permitido. Usa JPG o PDF.',
      FILE_SIZE: 'El archivo excede el tamano maximo de 5 MB.',
      AUTH_REQUIRED: 'Usuario no autenticado.',
      NO_FILE: 'Selecciona un archivo.'
    },
    UI: {
      MODAL_TITLE: 'Subir documento de identidad',
      CLOSE: 'Cerrar',
      PREVIEW_HINT: 'Selecciona JPG o PDF (<= 5MB) para previsualizar.',
      OPEN_BUTTON: 'Subir carnet',
      UPLOAD_BUTTON: 'Subir',
      UPLOADING: 'Subiendo...',
      CANCEL: 'Cancelar',
      SUCCESS: 'Documento subido correctamente.'
    }
  },
  VALIDATION: {
    NAME_MIN: 'El nombre debe tener al menos 2 caracteres.',
    NAME_MAX: 'El nombre no puede superar 80 caracteres.',
    AGE_MIN: 'La edad minima permitida es 18.',
    AGE_MAX: 'La edad maxima permitida es 99.',
    AVATAR_INVALID: 'La foto debe ser una URL valida o una imagen cargada.',
    BIO_MAX: 'La biografia no puede superar 280 caracteres.',
    LOCATION_MAX: 'La ubicacion no puede superar 120 caracteres.',
    BUDGET_MIN: 'El presupuesto minimo no puede ser negativo.',
    BUDGET_MAX: 'El presupuesto maximo no puede ser negativo.',
    BUDGET_RANGE: 'El presupuesto minimo no puede ser mayor al maximo.',
    FILE_TYPE: 'Formato no permitido. Usa JPG, PNG o WEBP.',
    FILE_SIZE: 'La imagen excede el tamano maximo de 3 MB.',
  },
  UI: {
    TITLE: 'Mi perfil',
    SUBTITLE: 'Completa y actualiza tus datos personales para mejorar tu perfil.',
    AVATAR_TITLE: 'Foto de perfil',
    AVATAR_HINT: 'Puedes pegar una URL o cargar una imagen desde tu dispositivo.',
    LABEL_NAME: 'Nombre',
    LABEL_AGE: 'Edad',
    LABEL_LOCATION: 'Ubicacion',
    LABEL_BIO: 'Biografia',
    LABEL_AVATAR_URL: 'URL de foto',
    LABEL_AVATAR_UPLOAD: 'Cargar foto',
    LABEL_BUDGET_MIN: 'Presupuesto minimo',
    LABEL_BUDGET_MAX: 'Presupuesto maximo',
    PLACEHOLDER_NAME: 'Tu nombre',
    PLACEHOLDER_AGE: 'Ej: 24',
    PLACEHOLDER_LOCATION: 'Ej: Medellin, Colombia',
    PLACEHOLDER_BIO: 'Cuentanos sobre ti y el tipo de roomie o propiedad que buscas.',
    PLACEHOLDER_AVATAR_URL: 'https://...',
    PLACEHOLDER_BUDGET_MIN: 'Ej: 800',
    PLACEHOLDER_BUDGET_MAX: 'Ej: 1200',
    SUBMIT: 'Guardar perfil',
    SAVING: 'Guardando...',
    LOADING: 'Cargando perfil...',
    LOAD_ERROR: 'No pudimos cargar tu perfil. Intenta nuevamente.',
    SAVE_SUCCESS: 'Perfil actualizado correctamente.',
    SAVE_ERROR: 'No pudimos guardar los cambios. Intenta nuevamente.',
    FILE_READY: 'Foto cargada correctamente.',
    FILE_CLEARED: 'Se limpio la foto cargada.',
    PREVIEW_ALT: 'Vista previa de foto de perfil',
  },
} as const
