// This file will be auto-generated by: npx supabase gen types typescript --project-id <your-project-id>
// For now it provides a placeholder type

export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
