export const AUTH = {
  MIN_PASSWORD_LENGTH: 8,
  MIN_NAME_LENGTH: 2,
  RATE_LIMIT_COOLDOWN_SECONDS: 60,
  VALIDATION: {
    EMAIL_INVALID: 'Email inválido',
    PASSWORD_MIN: 'Mínimo 8 caracteres',
    PASSWORDS_DO_NOT_MATCH: 'Las contraseñas no coinciden',
    NAME_TOO_SHORT: 'Nombre demasiado corto',
  },
  UI: {
    LOGIN_TITLE: 'Iniciar sesión',
    LOGIN_SUBTITLE: 'Bienvenido de vuelta',
    LOGIN_SUBMIT: 'Iniciar sesión',
    REGISTER_TITLE: 'Crear cuenta',
    REGISTER_SUBTITLE: 'Empieza a encontrar tu roomie ideal',
    REGISTER_SUBMIT: 'Crear cuenta',
    OAUTH_DIVIDER: 'o continúa con',
    LABEL_EMAIL: 'Email',
    LABEL_PASSWORD: 'Contraseña',
    LABEL_NEW_PASSWORD: 'Nueva contraseña',
    LABEL_CONFIRM_PASSWORD: 'Confirmar contraseña',
    LABEL_FULL_NAME: 'Nombre completo',
    FORGOT_PASSWORD: '¿Olvidaste tu contraseña?',
    FORGOT_PASSWORD_TITLE: 'Recuperar contraseña',
    FORGOT_PASSWORD_SUBTITLE: 'Te enviaremos un enlace seguro para restablecer tu acceso',
    FORGOT_PASSWORD_SUBMIT: 'Enviar enlace de recuperación',
    FORGOT_PASSWORD_SUCCESS:
      'Si el correo está registrado, recibirás un enlace para restablecer tu contraseña.',
    RESET_PASSWORD_TITLE: 'Establecer nueva contraseña',
    RESET_PASSWORD_SUBTITLE: 'Ingresa tu nueva contraseña para recuperar el acceso a tu cuenta',
    RESET_PASSWORD_SUBMIT: 'Actualizar contraseña',
    RESET_PASSWORD_SUCCESS: 'Tu contraseña fue actualizada correctamente. Ya puedes iniciar sesión.',
    VERIFY_EMAIL_TITLE: 'Verifica tu email',
    VERIFY_EMAIL_SUBTITLE:
      'Te enviamos un enlace de confirmación. Revisa tu bandeja de entrada y luego inicia sesión.',
    VERIFY_EMAIL_HINT: 'Si no lo encuentras, revisa spam o solicita un nuevo registro.',
    VERIFY_EMAIL_RESEND: 'Reenviar correo de confirmación',
    VERIFY_EMAIL_RESEND_SUCCESS: 'Correo de confirmación reenviado. Revisa tu bandeja de entrada.',
    VERIFY_EMAIL_RESEND_MISSING_EMAIL:
      'No detectamos el correo. Regístrate de nuevo para reenviar la confirmación.',
    VERIFY_EMAIL_RESEND_COOLDOWN: 'Espera {seconds}s para volver a reenviar el correo.',
    BACK_TO_LOGIN: 'Volver a iniciar sesión',
    NO_ACCOUNT: '¿No tienes cuenta? ',
    ALREADY_HAVE_ACCOUNT: '¿Ya tienes cuenta? ',
    LINK_LOGIN: 'Inicia sesión',
    LINK_REGISTER: 'Regístrate',
    GOOGLE_SIGN_IN: 'Continuar con Google',
    GOOGLE_SIGN_UP: 'Registrarse con Google',
    GOOGLE_RECOVERY_HINT:
      'Si tu cuenta fue creada con Google, gestiona tu acceso desde la cuenta de Google.',
    GOOGLE: 'Google',
    ERROR_RATE_LIMIT:
      'Demasiadas solicitudes en poco tiempo. Espera 60 segundos e intenta nuevamente.',
    ERROR_AUTH_GENERIC: 'No pudimos completar la solicitud. Intenta nuevamente en unos minutos.',
  },
  ROLES: {
    SEEKER: 'seeker',
    OWNER: 'owner',
    ADMIN: 'admin',
  },
  PLACEHOLDERS: {
    EMAIL: 'tu@email.com',
    PASSWORD: '••••••••',
    PASSWORD_HINT: 'Mínimo 8 caracteres',
    NEW_PASSWORD: 'Nueva contraseña segura',
    CONFIRM_PASSWORD: 'Repite tu nueva contraseña',
    FULL_NAME: 'Ana García',
  },
  ERROR_KEYS: {
    ROOT: 'root',
  },
} as const
