export const REVIEW_LABELS = {
  title: 'Reseñas de la comunidad',
  emptyTitle: 'Todavía no hay reseñas registradas',
  emptyDescription: 'Cuando una convivencia esté confirmada, las opiniones aparecerán aquí para orientar a otros usuarios.',
  summaryAverage: 'Calificación promedio',
  summaryTotal: 'Reseñas visibles',
  summaryConfirmed: 'Convivencias verificadas',
  formTitleUser: 'Escribe tu reseña sobre este roomie',
  formTitleProperty: 'Escribe tu reseña sobre esta propiedad',
  formHelper: 'Solo puedes publicar reseñas vinculadas a convivencias confirmadas.',
  confirmationLabel: 'Convivencia confirmada',
  ratingLabel: 'Calificación',
  commentLabel: 'Tu experiencia',
  commentPlaceholder: 'Describe cómo fue la convivencia, qué te gustó y qué debería saber la comunidad.',
  submitLabel: 'Publicar reseña',
  successMessage: 'Tu reseña ya quedó registrada y asociada al perfil correspondiente.',
  confirmedBadge: 'Convivencia confirmada',
  propertyAssociationPrefix: 'Asociada al perfil por estancia en',
  noEligibilityTitle: 'Aún no puedes reseñar este perfil o propiedad',
  noEligibilityDescription: 'Primero debe existir una convivencia confirmada para proteger la confianza de la comunidad.',
  demoReviewer: 'Modo demo activo: se usa un perfil de prueba para validar el flujo mientras llega el backend.',
} as const
