export { PrivacySection } from './components/privacy-section'
export { ToggleSwitch } from './components/toggle-switch'
export { usePrivacy } from './hooks/use-privacy'
export type { PrivacySettings, PrivacyOption, ToggleSwitchProps } from './types/privacy.types'
export { PRIVACY_OPTIONS, PRIVACY_DEFAULTS } from './constants/privacy.constants'
